version: 0.0
os: linux
files:
  - source: /
    destination: /home/nodejs
hooks:
  BeforeInstall:
    - location : after_install_script.sh
      runas: root
  ApplicationStart:
    - location : node_start.sh
      runas: root
