version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/nodejs
  - source: mongodb-org-4.0.repo
    destination: /etc/yum.repos.d
hooks:
  BeforeInstall:
     - location : after_install_script.sh
       runas: root
     - location : install_mongoDB.sh
       runas: root
  ApplicationStart:
    - location : node_start.sh
      runas: root
