version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/nodejs
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
      runas: root
  BeforeInstall:
    - location: after_install_script.sh
      runas: root
  ApplicationStart:
    - location: node_start.sh
    - location: register_with_elb.sh
      runas: root
